# -*- coding: utf-8 -*-

from xlcalcnet.mpmath import mp
from xlcalcnet.mpmath import plot

from xlcalcnet import fpm, mpm, gmp, ipm, dec, arb




def demo_rv_chisquared():
    mpm.dps = 30
    
    print("fpm:")
    rv = fpm.dist_chisquared(10)
    res = rv.pdf(8)
    print("pdf:", res)
    res = rv.cdf(15)
    print("cdf:", res)
    res = rv.sf(15)
    print("sf :", res)
    res = rv.qtf(0.6)
    print("qtf:", res)
    res = rv.isf(0.6)
    print("isf:", res)
    res = rv.c_x(0.2)
    print("c_x:", res)
    res = rv.m_x(0.2)
    print("m_x:", res)
    res = rv.k_x(0.2)
    print("k_x:", res)
    res = rv.saddleppoint('0.2')
    print("saddleppoint:", res)
    res = rv.cumulants(6)
    print("cumulants:", res)
    print()
    
    print("mpm:")
    rv = mpm.dist_chisquared(10)
    res = rv.pdf(8)
    print("pdf:", res)
    res = rv.cdf(15)
    print("cdf:", res)
    res = rv.sf(15)
    print("sf :", res)
    res = rv.qtf(0.6)
    print("qtf:", res)
    res = rv.isf(0.6)
    print("isf:", res)
    res = rv.c_x(0.2)
    print("c_x:", res)
    res = rv.m_x(0.2)
    print("m_x:", res)
    res = rv.k_x(0.2)
    print("k_x:", res)
    res = rv.saddleppoint('0.2')
    print("saddleppoint:", res)
    res = rv.cumulants(6)
    print("cumulants:", res)
    print()
    
    print("gpm:")
    rv = gmp.dist_chisquared(10)
    res = rv.pdf(8)
    print("pdf:", res)
    res = rv.cdf(15)
    print("cdf:", res)
    res = rv.sf(15)
    print("sf :", res)
    res = rv.qtf(0.6)
    print("qtf:", res)
    res = rv.isf(0.6)
    print("isf:", res)
    res = rv.c_x(0.2)
    print("c_x:", res)
    res = rv.m_x(0.2)
    print("m_x:", res)
    res = rv.k_x(0.2)
    print("k_x:", res)
    res = rv.saddleppoint('0.2')
    print("saddleppoint:", res)
    res = rv.cumulants(6)
    print("cumulants:", res)
    print()
    
    print("dec:")
    rv = dec.dist_chisquared(10)
    res = rv.pdf(8)
    print("pdf:", res)
    res = rv.cdf(15)
    print("cdf:", res)
    res = rv.sf(15)
    print("sf :", res)
    res = rv.qtf(0.6)
    print("qtf:", res)
    res = rv.isf(0.6)
    print("isf:", res)
#    res = rv.c_x(0.2)
#    print("c_x:", res)
    res = rv.m_x(0.2)
    print("m_x:", res)
    res = rv.k_x(0.2)
    print("k_x:", res)
    res = rv.saddleppoint('0.2')
    print("saddleppoint:", res)
    res = rv.cumulants(6)
    print("cumulants:", res)
    print()
    
    print("ipm:")
    rv = ipm.dist_chisquared(10)
    res = rv.pdf(8)
    print("pdf:", res)
    res = rv.cdf(15)
    print("cdf:", res)
    res = rv.sf(15)
    print("sf :", res)
    res = rv.qtf(0.6)
    print("qtf:", res)
    res = rv.isf(0.6)
    print("isf:", res)
    res = rv.c_x(0.2)
    print("c_x:", res)
    res = rv.m_x(0.2)
    print("m_x:", res)
    res = rv.k_x(0.2)
    print("k_x:", res)
    res = rv.saddleppoint('0.2')
    print("saddleppoint:", res)
    res = rv.cumulants(6)
    print("cumulants:", res)
    print()
    
    print("arb:")
    rv = arb.dist_chisquared(10)
    res = rv.pdf(8)
    print("pdf:", res)
    res = rv.cdf(15)
    print("cdf:", res)
    res = rv.sf(15)
    print("sf :", res)
    res = rv.qtf(0.6)
    print("qtf:", res)
    res = rv.isf(0.6)
    print("isf:", res)
    res = rv.c_x(0.2)
    print("c_x:", res)
    res = rv.m_x(0.2)
    print("m_x:", res)
    res = rv.k_x(0.2)
    print("k_x:", res)
    res = rv.saddleppoint('0.2')
    print("saddleppoint:", res)
    res = rv.cumulants(6)
    print("cumulants:", res)
    print()

    return


demo_rv_chisquared()
