#include <com/sun/star/uno/XInterface.idl>

module com{ module duhadler { module release { module MpFunlab {

    interface XMpFunlab
    {
      sequence< sequence< any > >   asdouble([in] string MpString);
      sequence< sequence< any > >   apy0([in] string Formula,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   apy1([in] string Formula,[in] any Param1,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   apy2([in] string Formula,[in] any Param1,[in] any Param2,[in] any Transposed, [in] any ShowShape);
      sequence< sequence< any > >   apy3([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   apy4([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Param4,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   apy5([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Param4,[in] any Param5,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   apy6([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Param4,[in] any Param5,[in] any Param6,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   apy7([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Param4,[in] any Param5,[in] any Param6,[in] any Param7,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   apy8([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Param4,[in] any Param5,[in] any Param6,[in] any Param7,[in] any Param8,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   apy9([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Param4,[in] any Param5,[in] any Param6,[in] any Param7,[in] any Param8,[in] any Param9,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   aspy0([in] string Formula,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   aspy1([in] string Formula,[in] any Param1,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   aspy2([in] string Formula,[in] any Param1,[in] any Param2,[in] any Transposed, [in] any ShowShape);
      sequence< sequence< any > >   aspy3([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   aspy4([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Param4,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   aspy5([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Param4,[in] any Param5,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   aspy6([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Param4,[in] any Param5,[in] any Param6,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   aspy7([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Param4,[in] any Param5,[in] any Param6,[in] any Param7,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   aspy8([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Param4,[in] any Param5,[in] any Param6,[in] any Param7,[in] any Param8,[in] any Transposed,[in] any ShowShape);
      sequence< sequence< any > >   aspy9([in] string Formula,[in] any Param1,[in] any Param2,[in] any Param3,[in] any Param4,[in] any Param5,[in] any Param6,[in] any Param7,[in] any Param8,[in] any Param9,[in] any Transposed,[in] any ShowShape);
};

}; }; }; };
